### ISSUE TITLE
Breach of license: Baldric Network

### ISSUE THREAD

**Issue by kailan** [commandstudio/commandstudio#12]
http://baldricnetwork.com/foro/topic/7dbf3ebac80febdbb7bd8c2e64c49abc ([mirror screenshot](https://i.imgur.com/dcYUqdb.png))
http://command.baldricnetwork.com/

Baldric "Network" are claiming to have created this as their own – no attribution or license included. This may be something you wish to look into.

cc: @RubeVi who appears to be a web dev for Baldric

**Comment by kailan** [comment]
This includes removal/modification of the "CommandStudio" attribution and information modal in the top right:
![scumbags](https://i.imgur.com/9CSGxKd.png)

**Comment by GalHorowitz** [comment]
-_\- The litterly claim they "developed" it -_-

**Comment by stuntguy3000** [comment]
That was fast, for shame.

**Comment by lemarcantoine** [comment]
At least they've put back the correct link. Thanks for alerting me. :)
