### ISSUE TITLE
Menu background is the same as text editor background

### ISSUE THREAD

**Issue by towerofnix** [commandstudio/commandstudio#24]
That makes menus look completely transparent when placed over the text editor, which isn't particularly friendly to people who freak out over things like that.

A box shadow on menus might not be a bad idea, either.

<img width="297" alt="screen shot 2016-11-28 at 9 34 23 pm" src="https://cloud.githubusercontent.com/assets/9948030/20693080/76f54df0-b5b2-11e6-926a-39baf2eb0f7d.png"> <img width="238" alt="screen shot 2016-11-28 at 9 35 48 pm" src="https://cloud.githubusercontent.com/assets/9948030/20693118/a66631bc-b5b2-11e6-8fdb-65a2af65adae.png">

**Comment by lemarcantoine** [comment]
You really love details haha. I'll keep these feedbacks in mind. :)
