### ISSUE TITLE
Am I doing this right? (Relating to program in-game creation timing)

### ISSUE THREAD

**Issue by towerofnix** [commandstudio/commandstudio#3]
Here's the most obvious way to get a program started:

```
i1: say Hello
say ..world.
```

However, it doesn't work - it only outputs `Hello`.

The reason for this is that `say ..world` _doesn't exist_ when `say Hello` is called.

It's not too hard to get the program to run after all the command blocks have been placed:

```
$root = -50 56 350 // or some other convenient location

position $root
i0: say Hello
say ..world.

i1: blockdata $root {auto:1b}

// I also like to attach a "clean up" block that gets rid of that blockdata
// block, but it's unnecessary:
i1: fill ~ ~-1 ~ ~ ~ ~ air 0 destroy
```

It makes sense:
1. Place a not-automatic impulse block.
2. Place automatic chain blocks.
3. Tell the impulse block to run. This will cause the chain blocks to also run, in sequence.
4. Optionally clean up (get rid of `blockdata` block).

..but it's not terribly obvious. Am I doing this right?

**Comment by liam4** [comment]
Hmm.. here's a program that seems to be much larger than necessary:

```
$init = -50 56 350
$loop = {# $init + 1 0 0 #}
$meta = {# $init + -1 0 0 #}

$initCreated = {# $init + 0 -1 0 #}
$loopCreated = {# $loop + 0 -1 0 #}

fill $initCreated $loopCreated air 0 replace lapis_block

position $init
i0:
scoreboard objectives add foo dummy
scoreboard objectives setdisplay sidebar foo
scoreboard players set GLOBAL foo 0
blockdata $loop {auto: 1b}
i1: setblock $initCreated lapis_block

position $loop
r0:
scoreboard players add GLOBAL foo 1
i1: setblock $loopCreated lapis_block

position $meta
i0:
r1: testforblock $initCreated lapis_block
c1?: testforblock $loopCreated lapis_block
c1?: blockdata $meta {auto: 0b}
c1?: blockdata $init {auto: 1b}
i1: blockdata $meta {auto: 1b}
```

* Clear any lapis "created marker" blocks.
* Create both command columns - when they're done being created they place a lapis "created marker" block below.
* Wait for the "created marker" blocks to be created in the "meta" section.
* Once created, start the "init" section.

But I think I have an idea of how to simplify this..

**Comment by liam4** [comment]
Mhm, this is much better:

```
$root = -50 56 350 // or some other convenient location

position $root

i0:
scoreboard objectives add foo dummy
scoreboard objectives setdisplay sidebar foo
scoreboard players set GLOBAL foo 0

r:
scoreboard players add GLOBAL foo 1

i1: blockdata $root {auto:1b}
```

**Comment by JBartelsson** [comment]
The problem here is the way Commandstudio creates the command blocks. They get created one by one as a `FallingSand` entity. Thats why `say ..world.` is non existent when `say Hello` is called. At the moment this one is a problem but don't worry it will be fixed soon! (There is a way to spawn the command blocks all at once with `MinecartCommandblock` entities stacked on top of eachother
