### ISSUE TITLE
Can't use selector that has arguments as a function argument

### ISSUE THREAD

**Issue by towerofnix** [commandstudio/commandstudio#4]
It thinks there's too many arguments:

```
def ^check_found($target, $selector)

^check_found(@e[tag=isGunpowder], @e[tag=isStick,r=1])
```

One of these should probably be able to work:

```
^check_found(@e[tag=isGunpowder], "@e[tag=isStick,r=1]") // quotes should be able to be \" escaped too!
^check_found(@e[tag=isGunpowder], @e[tag=isStick\,r=1])
```

**Comment by lemarcantoine** [comment]
Oh right, I've forgot to escape commas into def calls. I have no fix for the moment.

I like your string proposition. It'll get fixed when I'll rewrite the compilator engine.

**Comment by lemarcantoine** [comment]
I think I will change `,` to `;` for arguments separation since selectors often use commas.

**Comment by lemarcantoine** [comment]
Now we can escape commas, but in a future update, CommandStudio will use `;` to separate arguments.
