### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by GalHorowitz** [commandstudio/commandstudio#7]
More of a suggestion than a issue, but anyways:
When you write something like this:

```
$test = 5
$m = 3
say $test + $m
```

It will output:
`summon FallingSand ~ ~2 ~ {Block:chain_command_block,Data:1,TileEntityData:{Command:say 5 + 3,TrackOutput:0b,auto:1},Time:1}`
Suggested output
`summon FallingSand ~ ~2 ~ {Block:chain_command_block,Data:1,TileEntityData:{Command:say 8,TrackOutput:0b,auto:1},Time:1}`

**Comment by lemarcantoine** [comment]
I was thinking about it. It will come with the new compiler engine. :smile:

**Comment by towerofnix** [comment]
I'm curious, though, how does this get distinguished from normal text?

e.g. how would I say "3 + 4 = 7"? If it's done like in the original post, `3 + 4 = 3 + 4` would result in "7 = 7".. that's not what we're looking for. A piece of syntax to surround math could probably work, e.g. `3 + 4 = [3 + 4]`.

**Comment by GalHorowitz** [comment]
@liam4  Thats a great idea. The only problem, is if this will ever expanded to somekind of a real programming language, this will mess arrays. Maybe another symbol instead?

**Comment by towerofnix** [comment]
`{# coord-add #}` could be expanded to work with other math operators and operands, perhaps?

**Comment by lemarcantoine** [comment]
Yeah plus brackets are commonly used in JSON so it would be a nightmare. I think I will go for a simple syntax without surrounding characters and keep `{# #}` for coordinates.

And yes arrays will happen. :smile:
