### ISSUE TITLE
Backslash in command should cause the command to have quotation marks around out

### ISSUE THREAD

**Issue by Marcono1234** [commandstudio/commandstudio#9]
This is kind of an enhancement.

The Minecraft NBT parser parses backslashes in strings without quotation marks a little bit strange:
`/say \` > `/setblock ~ ~ ~ command_block 0 replace {Command:/say \}` > `/say \`
``/say \\` > `/setblock ~ ~ ~ command_block 0 replace {Command:/say \\}` > `/say \`

To prevent any confusion I would suggest having quotation marks around commands which contain backslashes and escaping all characters of the command as well.
`/say \\` > `/setblock ~ ~ ~ command_block 0 replace {Command:"/say \\\\"}` > `/say \\`

**Comment by lemarcantoine** [comment]
Fixed!
